
import { StateTariff, AppliancePreset } from './types';

export const INDIAN_STATES: StateTariff[] = [
  { id: 'andhra-pradesh', name: 'Andhra Pradesh', fixedCharge: 100, slabs: [{ min: 0, max: 50, rate: 1.45 }, { min: 51, max: 100, rate: 2.60 }, { min: 101, max: 200, rate: 3.60 }, { min: 201, max: null, rate: 6.65 }] },
  { id: 'telangana', name: 'Telangana', fixedCharge: 100, slabs: [{ min: 0, max: 50, rate: 1.45 }, { min: 51, max: 100, rate: 2.60 }, { min: 101, max: 200, rate: 3.60 }, { min: 201, max: null, rate: 6.70 }] },
  { id: 'tamil-nadu', name: 'Tamil Nadu', fixedCharge: 120, slabs: [{ min: 0, max: 100, rate: 2.00 }, { min: 101, max: 200, rate: 3.00 }, { min: 201, max: 500, rate: 4.60 }, { min: 501, max: null, rate: 6.60 }] },
  { id: 'karnataka', name: 'Karnataka', fixedCharge: 110, slabs: [{ min: 0, max: 50, rate: 2.05 }, { min: 51, max: 100, rate: 3.10 }, { min: 101, max: 200, rate: 4.20 }, { min: 201, max: null, rate: 6.95 }] },
  { id: 'kerala', name: 'Kerala', fixedCharge: 90, slabs: [{ min: 0, max: 50, rate: 2.80 }, { min: 51, max: 100, rate: 3.50 }, { min: 101, max: 200, rate: 4.90 }, { min: 201, max: null, rate: 6.80 }] },
  { id: 'maharashtra', name: 'Maharashtra', fixedCharge: 120, slabs: [{ min: 0, max: 100, rate: 3.36 }, { min: 101, max: 300, rate: 6.05 }, { min: 301, max: 500, rate: 9.81 }, { min: 501, max: null, rate: 11.07 }] },
  { id: 'gujarat', name: 'Gujarat', fixedCharge: 100, slabs: [{ min: 0, max: 50, rate: 3.20 }, { min: 51, max: 200, rate: 3.90 }, { min: 201, max: null, rate: 5.20 }] },
  { id: 'rajasthan', name: 'Rajasthan', fixedCharge: 120, slabs: [{ min: 0, max: 100, rate: 3.14 }, { min: 101, max: 200, rate: 4.00 }, { min: 201, max: null, rate: 5.90 }] },
  { id: 'uttar-pradesh', name: 'Uttar Pradesh', fixedCharge: 110, slabs: [{ min: 0, max: 100, rate: 3.35 }, { min: 101, max: 300, rate: 5.50 }, { min: 301, max: null, rate: 6.50 }] },
  { id: 'madhya-pradesh', name: 'Madhya Pradesh', fixedCharge: 95, slabs: [{ min: 0, max: 50, rate: 2.90 }, { min: 51, max: 150, rate: 4.00 }, { min: 151, max: null, rate: 5.80 }] },
  { id: 'west-bengal', name: 'West Bengal', fixedCharge: 110, slabs: [{ min: 0, max: 100, rate: 4.00 }, { min: 101, max: 300, rate: 5.50 }, { min: 301, max: null, rate: 6.80 }] },
  { id: 'delhi', name: 'Delhi', fixedCharge: 100, slabs: [{ min: 0, max: 200, rate: 3.00 }, { min: 201, max: 400, rate: 4.50 }, { min: 401, max: null, rate: 6.50 }] },
  { id: 'punjab', name: 'Punjab', fixedCharge: 120, slabs: [{ min: 0, max: 100, rate: 4.19 }, { min: 101, max: 300, rate: 6.64 }, { min: 301, max: null, rate: 7.20 }] },
  { id: 'haryana', name: 'Haryana', fixedCharge: 110, slabs: [{ min: 0, max: 100, rate: 2.50 }, { min: 101, max: 300, rate: 5.25 }, { min: 301, max: null, rate: 6.30 }] },
  { id: 'bihar', name: 'Bihar', fixedCharge: 90, slabs: [{ min: 0, max: 50, rate: 2.90 }, { min: 51, max: 200, rate: 4.10 }, { min: 201, max: null, rate: 5.50 }] },
  { id: 'odisha', name: 'Odisha', fixedCharge: 95, slabs: [{ min: 0, max: 50, rate: 3.00 }, { min: 51, max: 200, rate: 4.50 }, { min: 201, max: null, rate: 5.80 }] },
  { id: 'assam', name: 'Assam', fixedCharge: 100, slabs: [{ min: 0, max: 100, rate: 4.50 }, { min: 101, max: 300, rate: 5.50 }, { min: 301, max: null, rate: 6.50 }] }
];

export const APPLIANCE_LIBRARY: AppliancePreset[] = [
  {
    appliance_id: "ac_01",
    appliance_name: "Air Conditioner",
    category: "cooling",
    supports_standard_mode: true,
    supports_bee_annual_mode: true,
    supports_iseer_mode: true,
    default_energy_mode: "iseer",
    typical_daily_usage_hours: 8,
    quantity_default: 1,
    is_inverter: true,
    capacity_ton_options: [0.75, 1.0, 1.5, 2.0],
    default_capacity_ton: 1.5,
    iseer_range: { min: 3.5, max: 6.0 },
    default_iseer: 4.8,
    iseer_note: "Higher ISEER = Lower power consumption. Check your AC's BEE Star Label.",
    wattage_options: [800, 1200, 1500, 2200],
    default_wattage: 1500,
    typical_annual_energy_kwh: 850,
    bee_label_note: "Refer to the 'Units per Year' value on the BEE Star Label.",
    icon: "🌬️",
    notes: "Configure as Inverter (ISEER) or Fixed Speed (Standard) in the next step."
  },
  {
    appliance_id: "refrigerator_01",
    appliance_name: "Refrigerator",
    category: "cooling",
    supports_standard_mode: true,
    supports_bee_annual_mode: true,
    supports_iseer_mode: false,
    default_energy_mode: "bee_annual",
    typical_daily_usage_hours: 24,
    quantity_default: 1,
    typical_annual_energy_kwh: 260,
    bee_label_note: "Check the 'Electricity Consumption - Units per Year' on the BEE Star Label.",
    wattage_options: [100, 150, 250, 400],
    default_wattage: 150,
    icon: "❄️",
    notes: "Runs 24/7. Use BEE Annual value for accuracy."
  },
  {
    appliance_id: "ceiling_fan_01",
    appliance_name: "Ceiling Fan",
    category: "cooling",
    supports_standard_mode: true,
    supports_bee_annual_mode: false,
    supports_iseer_mode: false,
    default_energy_mode: "standard",
    typical_daily_usage_hours: 12,
    quantity_default: 3,
    wattage_options: [28, 35, 50, 75],
    default_wattage: 75,
    icon: "🎐",
    notes: "Standard fans: ~75W, BLDC fans: ~28W-35W."
  },
  {
    appliance_id: "led_bulb_01",
    appliance_name: "LED Bulb",
    category: "lighting",
    supports_standard_mode: true,
    supports_bee_annual_mode: false,
    supports_iseer_mode: false,
    default_energy_mode: "standard",
    typical_daily_usage_hours: 6,
    quantity_default: 5,
    wattage_options: [5, 7, 9, 12, 15, 18],
    default_wattage: 9,
    icon: "💡",
    notes: "Energy-efficient lighting."
  },
  {
    appliance_id: "tube_light_01",
    appliance_name: "Tube Light",
    category: "lighting",
    supports_standard_mode: true,
    supports_bee_annual_mode: false,
    supports_iseer_mode: false,
    default_energy_mode: "standard",
    typical_daily_usage_hours: 6,
    quantity_default: 2,
    wattage_options: [18, 20, 36, 40],
    default_wattage: 20,
    icon: "🕯️",
    notes: "LED tubes are usually 18-20W, older T12 tubes are 40W."
  },
  {
    appliance_id: "television_01",
    appliance_name: "Television",
    category: "electronics",
    supports_standard_mode: true,
    supports_bee_annual_mode: true,
    supports_iseer_mode: false,
    default_energy_mode: "standard",
    typical_daily_usage_hours: 5,
    quantity_default: 1,
    wattage_options: [50, 80, 100, 150, 200],
    default_wattage: 100,
    typical_annual_energy_kwh: 120,
    icon: "📺",
    notes: "LED TVs are efficient; larger screens consume more."
  },
  {
    appliance_id: "washing_machine_01",
    appliance_name: "Washing Machine",
    category: "motor",
    supports_standard_mode: true,
    supports_bee_annual_mode: true,
    supports_iseer_mode: false,
    default_energy_mode: "standard",
    typical_daily_usage_hours: 1,
    quantity_default: 1,
    wattage_options: [300, 500, 2000, 2500],
    default_wattage: 500,
    typical_annual_energy_kwh: 40,
    icon: "🧺",
    notes: "Heating cycle (hot wash) increases wattage significantly."
  },
  {
    appliance_id: "water_heater_01",
    appliance_name: "Water Heater (Geyser)",
    category: "heating",
    supports_standard_mode: true,
    supports_bee_annual_mode: false,
    supports_iseer_mode: false,
    default_energy_mode: "standard",
    typical_daily_usage_hours: 1,
    quantity_default: 1,
    wattage_options: [1500, 2000, 3000],
    default_wattage: 2000,
    icon: "🚿",
    notes: "High wattage appliance. Keep thermostat at 60°C."
  },
  {
    appliance_id: "microwave_01",
    appliance_name: "Microwave",
    category: "heating",
    supports_standard_mode: true,
    supports_bee_annual_mode: false,
    supports_iseer_mode: false,
    default_energy_mode: "standard",
    typical_daily_usage_hours: 0.5,
    quantity_default: 1,
    wattage_options: [800, 1000, 1200, 1500],
    default_wattage: 1200,
    icon: "🍲",
    notes: "Used for short bursts, but very high power."
  },
  {
    appliance_id: "mixer_grinder_01",
    appliance_name: "Mixer Grinder",
    category: "motor",
    supports_standard_mode: true,
    supports_bee_annual_mode: false,
    supports_iseer_mode: false,
    default_energy_mode: "standard",
    typical_daily_usage_hours: 0.5,
    quantity_default: 1,
    wattage_options: [500, 750, 1000],
    default_wattage: 750,
    icon: "🌪️",
    notes: "Common kitchen appliance."
  },
  {
    appliance_id: "laptop_01",
    appliance_name: "Laptop",
    category: "electronics",
    supports_standard_mode: true,
    supports_bee_annual_mode: false,
    supports_iseer_mode: false,
    default_energy_mode: "standard",
    typical_daily_usage_hours: 8,
    quantity_default: 1,
    wattage_options: [45, 65, 90, 120],
    default_wattage: 65,
    icon: "💻",
    notes: "Power usage varies based on performance."
  },
  {
    appliance_id: "desktop_01",
    appliance_name: "Desktop PC",
    category: "electronics",
    supports_standard_mode: true,
    supports_bee_annual_mode: false,
    supports_iseer_mode: false,
    default_energy_mode: "standard",
    typical_daily_usage_hours: 6,
    quantity_default: 1,
    wattage_options: [150, 250, 400, 600],
    default_wattage: 250,
    icon: "🖥️",
    notes: "Includes monitor and CPU tower."
  },
  {
    appliance_id: "iron_box_01",
    appliance_name: "Iron Box",
    category: "heating",
    supports_standard_mode: true,
    supports_bee_annual_mode: false,
    supports_iseer_mode: false,
    default_energy_mode: "standard",
    typical_daily_usage_hours: 0.5,
    quantity_default: 1,
    wattage_options: [750, 1000, 1250, 1500],
    default_wattage: 1000,
    icon: "👔",
    notes: "Heavy load for short duration."
  },
  {
    appliance_id: "water_pump_01",
    appliance_name: "Water Pump",
    category: "motor",
    supports_standard_mode: true,
    supports_bee_annual_mode: false,
    supports_iseer_mode: false,
    default_energy_mode: "standard",
    typical_daily_usage_hours: 1,
    quantity_default: 1,
    wattage_options: [375, 750, 1125, 1500],
    default_wattage: 750,
    icon: "🚰",
    notes: "0.5 HP = 375W, 1 HP = 750W."
  },
  {
    appliance_id: "exhaust_fan_01",
    appliance_name: "Exhaust Fan",
    category: "cooling",
    supports_standard_mode: true,
    supports_bee_annual_mode: false,
    supports_iseer_mode: false,
    default_energy_mode: "standard",
    typical_daily_usage_hours: 4,
    quantity_default: 1,
    wattage_options: [30, 50, 70],
    default_wattage: 50,
    icon: "🌀",
    notes: "Used in kitchens and bathrooms."
  }
];
